const API_KEY = '2c37293f0a591737be705bcd5d9325e1';
const TOKEN =
  'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyYzM3MjkzZjBhNTkxNzM3YmU3MDViY2Q1ZDkzMjVlMSIsIm5iZiI6MTcyMjQyNzQxOS4xODUsInN1YiI6IjY2YWEyODFiMWI2ZTIyNmMxMGExMGNjMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.8UXfbyi_xKgxq-_3zYJ494Z5-eV-MI6qOd4pQv0f8hg';

enum sections {
  POPULERTV= 'POPULERTV',
  POPULERMOVIES= 'POPULERMOVIES',
  TOPRATEDMOVIES= 'TOPRATEDMOVIES',
  TOPRATEDTV= 'TOPRATEDTV',
}
enum itemTypes {
 MOVIE= 'MOVIE',
 TV= 'TV',
}

export {API_KEY, TOKEN,sections,itemTypes};
